packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - "apps/**"
  - 'packages/**'
  # if required, exclude some directories
  - '!**/test/**'
allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  unrs-resolver: set this to true or false
