export const characters = [
  "a knight",
  "a wizard",
  "a detective",
  "a cowboy",
  "a dragon",
  "a barbarian",
  "a zombie",
  "a vampire",
  "a pirate",
  "a samurai",
  "an elf",
  "a time guardian",
  "a mermaid",
  "a robot",
  "a ninja",
  "a werewolf",
  "a superhero",
  "a sorcerer",
  "a banana",
  "a princess",
  "a scientist",
  "a ghost",
  "a teardrop",
  "a time traveler",
  "a witch",
  "a space explorer",
  "a talking cat",
  "a musician",
  "a chef",
  "a circus performer",
  "a fortune teller",
  "a knight's squire",
  "a street magician",
  "a secret agent",
  "an alien",
  "a caveman",
  "a gladiator",
  "a robot assistant",
  "a parkour expert",
  "a cyborg",
  "a painter",
  "a journalist",
  "a wrestler",
  "a guardian angel",
  "a fairy",
  "a ventriloquist",
  "a master thief",
  "a jester",
  "an athlete",
  "a bounty hunter",
  "an ant",
  "a giant",
  "a giant robot",
  "a frog",
  "a talking dog",
];

export const plots = [
  "trying to make peace with dragons after years of war",
  "leading an army against an invading force",
  "fighting the aliens who have invaded Earth",
  "journeying through time to change the course of history",
  "trying to be a king in a world of magic",
  "trying to find love in a world of magic",
  "trying to find a way to start sewing",
  "building a cabin in the woods",
  "trying to find a way to be a human again",
  "on a quest to retrieve a stolen artifact",
  "living in a world where magic is outlawed",
  "investigating a series of mysterious disappearances",
  "stranded on a deserted island and searching for a way home",
  "uncovering a conspiracy in a dystopian society",
  "trying to save a dying magical realm",
  "competing in a high-stakes, winner-takes-all tournament",
  "solving a murder mystery in a small town",
  "escaping from a maximum-security prison",
  "discovering hidden powers and abilities",
  "unraveling the secrets of an ancient civilization",
  "defending the kingdom against an invading army",
  "trying to be a queen of thieves",
  "forming an unlikely alliance to stop an evil sorcerer",
  "exploring a haunted mansion filled with restless spirits",
  "participating in a heist to steal a priceless artifact",
  "surviving in a post-apocalyptic wasteland",
  "discovering a portal to a parallel dimension",
  "seeking revenge against a treacherous betrayer",
  "finding the lost city of gold",
  "rescuing a kidnapped loved one from a criminal syndicate",
  "infiltrating a secret society with nefarious intentions",
  "leading a rebellion against an oppressive regime",
  "uncovering the truth behind a government conspiracy",
  "exploring an enchanted forest filled with magical creatures",
  "hunting down legendary creatures for fame and fortune",
  "challenging a powerful deity for control of the divine realm",
  "unraveling the mystery behind a cursed artifact",
  "building a utopian society from scratch",
  "training as a master martial artist to seek justice",
  "sailing the seas as a notorious pirate captain",
  "negotiating peace between warring factions",
  "surviving a zombie apocalypse and finding a safe haven",
  "seeking redemption for past sins through heroic deeds",
  "competing in a dangerous race across treacherous terrain",
  "exploring the depths of space as an intergalactic explorer",
  "overcoming personal fears and insecurities",
  "uncovering the truth behind a family curse",
  "joining a group of rebels fighting against a tyrannical ruler",
  "discovering a long-lost civilization hidden in the jungle",
  "escaping from a virtual reality simulation gone wrong",
  "protecting a magical artifact from falling into the wrong hands",
  "investigating a series of supernatural phenomena",
  "finding a cure for a deadly pandemic",
  "revanging the death of a loved one",
];

export const items = [
  "a sword",
  "a shield",
  "a bow",
  "arrows",
  "a gun",
  "a knife",
  "a rope",
  "a staff",
  "a magical amulet",
  "a grappling hook",
  "a lantern",
  "lockpicks",
  "a spellbook",
  "a compass",
  "a map",
  "a bag of holding",
  "throwing knives",
  "a flute",
  "a invisibility potion",
  "lockpicking tools",
  "a telescope",
  "climbing gear",
  "a net",
  "a vial of poison",
  "a shovel",
  "a crowbar",
  "a vial of acid",
  "a grappling rope",
  "darts",
  "a spyglass",
  "a bag of marbles",
  "a lockbox",
  "a smoke bomb",
  "disguise tools",
  "a telescope",
  "tracking tools",
  "sleep potion",
  "a bag of herbs",
  "a vial of poison",
  "a water bottle",
  "a fishing rod",
  "a guitar",
];

export const lessUsefulItems = [
  "A set of keys",
  "A lockpick",
  "A grappling rope",
  "A crowbar",
  "A lantern",
  "A compass",
  "A map",
  "A spyglass",
  "A bottle of potion",
  "A bag of coins",
  "A rope ladder",
  "A set of tools",
  "A first aid kit",
  "A tinderbox",
  "A bag of herbs",
  "A vial of poison",
  "A water canteen",
  "A fishing rod",
  "A set of playing cards",
  "A musical instrument",
  "A bag of marbles",
  "A bag of flour",
  "A whistle",
  "A mirror",
  "A magnifying glass",
  "A pair of binoculars",
  "A grappling hook",
  "A shovel",
  "A hammer",
  "A set of nails",
  "A cooking pot",
  "A tent",
  "A backpack",
  "A compass",
  "A pocket watch",
  "A journal",
  "A roll of bandages",
  "A bag of chalk",
  "A lantern",
  "A mirror",
  "A flask",
  "A walking stick",
  "A quill pen",
  "A set of dice",
  "A sewing kit",
  "A musical instrument",
  "A magnifying glass",
  "A lockbox",
  "A bottle of ink",
  "A pair of binoculars",
  "A whistle",
];

export const genres = [
  {
    name: "Fantasy",
    description:
      "Step into a realm where magic reigns supreme, as you embark on an extraordinary adventure through fantastical landscapes. Encounter mythical creatures, unravel ancient prophecies, and test your mettle against formidable foes in a battle of light against darkness. Your choices will shape the destiny of this enchanting world, where heroes are forged and legends are born.",
    image: "/img/categories/fantasy.png",
  },
  {
    name: "Adventure",
    description:
      "Embark on an adrenaline-fueled adventure of a lifetime, where uncharted territories await your exploration and every moment is a thrilling leap into the unknown. Discover the courage within as you navigate treacherous landscapes, conquer formidable challenges, and create a legacy that will be whispered in tales of daring exploits for generations to come.",
    image: "/img/categories/adventure.png",
  },
  {
    name: "Comedy",
    description:
      "Enter a world where laughter is the ultimate currency as you embark on a rib-tickling adventure filled with comedic chaos, witty hijinks, and unforgettable punchlines. Brace yourself for a comedic rollercoaster ride that will leave you in stitches and remind you that laughter truly is the best medicine.",
    image: "/img/categories/comedy.png",
  },
  {
    name: "Horror",
    description:
      "Enter a nightmarish realm where shadows lurk in every corner, and chilling whispers send shivers down your spine. Brace yourself for a bone-chilling descent into darkness as you confront your deepest fears and unearth the terrifying secrets that lie hidden in the shadows, knowing that survival is not guaranteed in this realm of relentless horror.",
    image: "/img/categories/horror.png",
  },
  {
    name: "Mystery",
    description:
      "Immerse yourself in a gripping world of secrets and deception, where every step forward uncovers new enigmas, and the truth lies hidden in the shadows, waiting to be unveiled. Follow a trail of clues, solve perplexing puzzles, and unravel the layers of a captivating mystery that will keep you guessing until the final, mind-bending revelation.",
    image: "/img/categories/mystery.png",
  },
  {
    name: "Romance",
    description:
      "Indulge in a whirlwind of passion and desire as you enter a realm where hearts entwine and love's intoxicating spell weaves its magic. Follow the journey of two souls destined to collide, navigating obstacles, experiencing heartache and bliss, ultimately discovering that true love is a force that transcends time and defies all odds.",
    image: "/img/categories/romance.png",
  },
  {
    name: "Sci-Fi",
    description:
      "Embark on an awe-inspiring voyage through the cosmos, where futuristic technologies and mind-bending possibilities await at every turn. Immerse yourself in a world of advanced civilizations, extraordinary discoveries, and epic intergalactic battles as you explore the vastness of the universe and contemplate the profound mysteries of existence.",
    image: "/img/categories/sci-fi.png",
  },
  {
    name: "Historical",
    description:
      "Travel back in time to an era steeped in rich traditions, grandeur, and momentous events that shaped the course of history. Immerse yourself in the captivating narratives of legendary figures, witness the rise and fall of empires, and experience the triumphs and tribulations of bygone eras, all within the tapestry of a meticulously researched and evocative historical setting.",
    image: "/img/categories/historical.png",
  },
  {
    name: "Dystopian",
    description:
      "Enter a dystopian world where the remnants of civilization struggle for survival amidst oppressive regimes, desolate landscapes, and the haunting echoes of a once-thriving society. Brace yourself for a harrowing journey that explores the depths of human resilience, challenging the boundaries of hope and presenting a stark reflection of a dark and uncertain future.",
    image: "/img/categories/dystopian.png",
  },
];
