import { CharacterStory } from "./story-creator";

export function getStory(): CharacterStory {
  const characters = [
    "a knight",
    "a banana",
    "a cowboy",
    "a teardrop",
    "a dragon",
    "a barbarian",
    "a zombie",
    "a vampire",
    "a pirate",
    "an elf",
    "a mermaid",
    "a robot",
    "a ninja",
    "a werewolf",
    "a sorcerer",
    "a princess",
    "a detective",
    "a scientist",
    "a ghost",
    "a time traveler",
    "a witch",
    "a superhero",
    "a space explorer",
    "a talking cat",
    "a musician",
    "a chef",
    "a circus performer",
    "a fortune teller",
    "a knight's squire",
    "a street magician",
    "a secret agent",
    "an alien",
    "a caveman",
    "a gladiator",
    "a samurai",
    "a robot assistant",
    "a parkour expert",
    "a cyborg",
    "a painter",
    "a journalist",
    "a wrestler",
    "a guardian angel",
    "a time guardian",
    "a fairy",
    "a ventriloquist",
    "a master thief",
    "a jester",
    "a professional athlete",
    "a bounty hunter",
    "a wizard",
    "an ant",
    "a giant",
    "a giant robot",
    "a frog",
    "a talking dog",
  ];

  const plots = [
    "trying to make peace with dragons after years of war",
    "with two pistols fighting the aliens",
    "in the ocean, trying to be a king",
    "trying to find love",
    "trying to find a way to start sewing",
    "trying to find a way to be a human again",
    "on a quest to retrieve a stolen artifact",
    "investigating a series of mysterious disappearances",
    "stranded on a deserted island and searching for a way home",
    "uncovering a conspiracy in a dystopian society",
    "trying to save a dying magical realm",
    "competing in a high-stakes, winner-takes-all tournament",
    "solving a murder mystery in a small town",
    "escaping from a maximum-security prison",
    "discovering hidden powers and abilities",
    "unraveling the secrets of an ancient civilization",
    "defending the kingdom against an invading army",
    "forming an unlikely alliance to stop an evil sorcerer",
    "exploring a haunted mansion filled with restless spirits",
    "participating in a heist to steal a priceless artifact",
    "journeying through time to change the course of history",
    "surviving in a post-apocalyptic wasteland",
    "discovering a portal to a parallel dimension",
    "seeking revenge against a treacherous betrayer",
    "finding the lost city of gold",
    "rescuing a kidnapped loved one from a criminal syndicate",
    "infiltrating a secret society with nefarious intentions",
    "leading a rebellion against an oppressive regime",
    "uncovering the truth behind a government conspiracy",
    "exploring an enchanted forest filled with magical creatures",
    "hunting down legendary creatures for fame and fortune",
    "challenging a powerful deity for control of the divine realm",
    "unraveling the mystery behind a cursed artifact",
    "building a utopian society from scratch",
    "training as a master martial artist to seek justice",
    "sailing the seas as a notorious pirate captain",
    "negotiating peace between warring factions",
    "surviving a zombie apocalypse and finding a safe haven",
    "seeking redemption for past sins through heroic deeds",
    "competing in a dangerous race across treacherous terrain",
    "exploring the depths of space as an intergalactic explorer",
    "overcoming personal fears and insecurities",
    "uncovering the truth behind a family curse",
    "joining a group of rebels fighting against a tyrannical ruler",
    "discovering a long-lost civilization hidden in the jungle",
    "escaping from a virtual reality simulation gone wrong",
    "protecting a magical artifact from falling into the wrong hands",
    "investigating a series of supernatural phenomena",
    "finding a cure for a deadly pandemic",
    "revanging the death of a loved one",
  ];

  const randomCharacter =
    characters[Math.floor(Math.random() * characters.length)];

  const randomStory = plots[Math.floor(Math.random() * plots.length)];

  return {
    plot: randomStory,
    characterType: randomCharacter,
  };
}
